baseURL = "http://weblogic.cafe/"
languageCode = "en-us"
title = "WebLogic Café"
theme = "ananke"
publishDir = "docs"
#disqusShortname = "markxnelson"
googleAnalytics = "UA-129126578-1"
copyright = "Copyright (c) 2018, Mark Nelson"
relativeURLs = true

[params]
  featured_image = "/images/cafe.jpg"
  body_classes = "avenir bg-near-white"
