baseURL = "http://weblogic.cafe/"
languageCode = "en-us"
title = "WebLogic Café"
theme = "ananke"
publishDir = "docs"
disqusShortname = "weblogic-cafe"
googleAnalytics = "UA-129126578-1"
copyright = "Copyright (c) 2018, Mark Nelson"
relativeURLs = true

[params]
  featured_image = "/images/cafe.jpg"
  body_classes = "avenir bg-near-white"
  twitter = "https://twitter.com/markxnelson"
  linkedin = "https://www.linkedin.com/in/marknelson6/"
  github = "https://github.com/markxnelson"
  show_reading_time = true
  favicon = "/favicon.ico"

[taxonomies]
  tag = "tags"
